### ISSUE TITLE
Feature Request: more Grafana Dashboards

### ISSUE THREAD

**Issue by rdxmb** [vfm/syseleven-exporter-chart#9]
Hello, thanks for this project.

I need some other dashboards, e.g. 

- quota in percent as TimeSeries
- single stat panels
- use project as template variable with rows repeated per project *)

Are you interested in a PR?

*) preview:

![Screenshot_20221129_175859](https://user-images.githubusercontent.com/30314040/204594472-806d6eba-5309-4975-9caa-f298c7953030.png)

**Comment by ghost** [comment]
Sure, LGTM
